"""Postgres StorageBackend (MCM2-08).

The first non-embedded reference. Implements the StorageBackend Protocol
against Postgres 15+, with tsvector generated columns + GIN indexes per
docs/schema-migration-v6-to-postgres.md. No separate FTS tables, no
sync triggers — Postgres handles search-index population inline via the
generated column.
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any, Iterator, Optional

if TYPE_CHECKING:
    import psycopg

from ...backends import (
    CONTRACT_VERSION,
    Capability,
    EntityType,
    MissingDependencyError,
    ErrorRow,
    KnowledgeRow,
    NegativeRow,
    RelationRow,
    RuleRow,
    SessionRow,
    SnapshotRow,
)


# ---------------------------------------------------------------------------
# DDL — mirrors docs/schema-migration-v6-to-postgres.md exactly.
# ---------------------------------------------------------------------------

_DDL_STATEMENTS: list[str] = [
    """
    CREATE TABLE IF NOT EXISTS knowledge (
        id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        topic                TEXT NOT NULL,
        kind                 TEXT NOT NULL DEFAULT 'finding',
        summary              TEXT NOT NULL,
        detail               TEXT,
        tags                 TEXT,
        project              TEXT,
        rationale            TEXT,
        alternatives         TEXT,
        hit_count            INTEGER NOT NULL DEFAULT 0,
        last_hit_at          TIMESTAMPTZ,
        reinforcement_count  INTEGER NOT NULL DEFAULT 0,
        pinned               BOOLEAN NOT NULL DEFAULT FALSE,
        created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
        tsv  tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(topic, '')),   'A') ||
            setweight(to_tsvector('english', coalesce(summary, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(detail, '')),  'C') ||
            setweight(to_tsvector('english', coalesce(tags, '')),    'D') ||
            setweight(to_tsvector('english', coalesce(kind, '')),    'D')
        ) STORED
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_knowledge_tsv      ON knowledge USING GIN (tsv)",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_project  ON knowledge (project) WHERE project IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_pinned   ON knowledge (pinned) WHERE pinned",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_last_hit ON knowledge (last_hit_at DESC NULLS LAST)",

    """
    CREATE TABLE IF NOT EXISTS negative_knowledge (
        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category          TEXT NOT NULL,
        what_failed       TEXT NOT NULL,
        why_failed        TEXT,
        correct_approach  TEXT,
        severity          TEXT NOT NULL DEFAULT 'normal',
        project           TEXT,
        pinned            BOOLEAN NOT NULL DEFAULT FALSE,
        created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
        tsv  tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(category, '')),         'A') ||
            setweight(to_tsvector('english', coalesce(what_failed, '')),      'B') ||
            setweight(to_tsvector('english', coalesce(why_failed, '')),       'C') ||
            setweight(to_tsvector('english', coalesce(correct_approach, '')), 'C')
        ) STORED
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_negative_tsv     ON negative_knowledge USING GIN (tsv)",
    "CREATE INDEX IF NOT EXISTS idx_negative_project ON negative_knowledge (project) WHERE project IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_negative_pinned  ON negative_knowledge (pinned) WHERE pinned",

    """
    CREATE TABLE IF NOT EXISTS errors (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pattern     TEXT NOT NULL,
        context     TEXT,
        root_cause  TEXT,
        fix         TEXT,
        tags        TEXT,
        project     TEXT,
        pinned      BOOLEAN NOT NULL DEFAULT FALSE,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        tsv  tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(pattern, '')),    'A') ||
            setweight(to_tsvector('english', coalesce(root_cause, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(fix, '')),        'B') ||
            setweight(to_tsvector('english', coalesce(context, '')),    'C') ||
            setweight(to_tsvector('english', coalesce(tags, '')),       'D')
        ) STORED
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_errors_tsv     ON errors USING GIN (tsv)",
    "CREATE INDEX IF NOT EXISTS idx_errors_project ON errors (project) WHERE project IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_errors_pinned  ON errors (pinned) WHERE pinned",

    """
    CREATE TABLE IF NOT EXISTS sessions (
        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status            TEXT NOT NULL,
        current_task      TEXT,
        findings_summary  TEXT,
        next_steps        TEXT,
        blockers          TEXT,
        context_snapshot  TEXT,
        created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,

    """
    CREATE TABLE IF NOT EXISTS rules (
        id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title                TEXT NOT NULL,
        keywords             TEXT NOT NULL,
        file_path            TEXT,
        description          TEXT,
        category             TEXT,
        hit_count            INTEGER NOT NULL DEFAULT 0,
        last_hit_at          TIMESTAMPTZ,
        reinforcement_count  INTEGER NOT NULL DEFAULT 0,
        pinned               BOOLEAN NOT NULL DEFAULT FALSE,
        created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
        content_hash         TEXT,
        archived_at          TIMESTAMPTZ,
        archived             BOOLEAN NOT NULL DEFAULT FALSE,
        tsv  tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(title, '')),       'A') ||
            setweight(to_tsvector('english', coalesce(keywords, '')),    'B') ||
            setweight(to_tsvector('english', coalesce(description, '')), 'C') ||
            setweight(to_tsvector('english', coalesce(category, '')),    'D')
        ) STORED
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_rules_tsv         ON rules USING GIN (tsv)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_rules_path ON rules (file_path) WHERE file_path IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_rules_archived    ON rules (archived)",

    """
    CREATE TABLE IF NOT EXISTS relations (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_type  TEXT NOT NULL,
        source_id    BIGINT NOT NULL,
        target_type  TEXT NOT NULL,
        target_id    BIGINT NOT NULL,
        relation     TEXT NOT NULL,
        note         TEXT,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (source_type, source_id, target_type, target_id, relation)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_relations_source ON relations (source_type, source_id)",
    "CREATE INDEX IF NOT EXISTS idx_relations_target ON relations (target_type, target_id)",

    """
    CREATE TABLE IF NOT EXISTS snapshots (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id      BIGINT REFERENCES sessions(id),
        sequence_num    INTEGER NOT NULL,
        goal            TEXT,
        progress        TEXT,
        open_questions  TEXT,
        blockers        TEXT,
        next_steps      TEXT,
        active_files    TEXT,
        key_decisions   TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_snapshots_session ON snapshots (session_id, sequence_num)",

    """
    CREATE TABLE IF NOT EXISTS _mcm_versions (
        component   TEXT PRIMARY KEY,
        version     INTEGER NOT NULL,
        updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,

    # -----------------------------------------------------------------
    # LODESTONE additive columns + tables.
    #
    # Option B per lodestone-lite-plan.md: extend `knowledge` with the
    # Claim axes (subject_keys[], governance_tags[], scope, status,
    # provenance) rather than introducing a separate Claim row shape.
    # The change is additive — existing consumers (agent_tricks,
    # retrodoc, cminer, every other session that calls add_knowledge)
    # are unaffected. No CONTRACT_VERSION bump.
    #
    # ALTER TABLE ... ADD COLUMN takes an AccessExclusiveLock even
    # when the column already exists. Wrapping the ALTERs in
    # information_schema lookups makes the repeated-apply path (every
    # DDL run after the first) a pure read, which doesn't block
    # readers holding ordinary locks on the table.
    # -----------------------------------------------------------------
    """
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name = 'knowledge' AND column_name = 'subject_keys') THEN
            ALTER TABLE knowledge ADD COLUMN subject_keys TEXT[];
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name = 'knowledge' AND column_name = 'governance_tags') THEN
            ALTER TABLE knowledge ADD COLUMN governance_tags TEXT[];
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name = 'knowledge' AND column_name = 'scope') THEN
            ALTER TABLE knowledge ADD COLUMN scope TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name = 'knowledge' AND column_name = 'status') THEN
            ALTER TABLE knowledge ADD COLUMN status TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name = 'knowledge' AND column_name = 'provenance') THEN
            ALTER TABLE knowledge ADD COLUMN provenance JSONB;
        END IF;
    END$$
    """,
    "CREATE INDEX IF NOT EXISTS idx_knowledge_subject_keys ON knowledge USING GIN (subject_keys)",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_governance   ON knowledge USING GIN (governance_tags)",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_scope        ON knowledge (scope)  WHERE scope  IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_status       ON knowledge (status) WHERE status IS NOT NULL",

    # Bearer-token table: one row per minted token. The streamable-
    # HTTP transport middleware validates incoming Authorization
    # headers against token_hash; rows with non-null revoked_at are
    # treated as absent.
    """
    CREATE TABLE IF NOT EXISTS tokens (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token_hash    TEXT NOT NULL UNIQUE,
        principal     TEXT NOT NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        revoked_at    TIMESTAMPTZ,
        last_used_at  TIMESTAMPTZ
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_tokens_principal ON tokens (principal)",

    # Recall log: append-only audit trail. A successful kb_recall
    # writes one row here and DELETEs the corresponding knowledge
    # row. Rows persist after the claim is gone.
    """
    CREATE TABLE IF NOT EXISTS recall_log (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        claim_id    BIGINT NOT NULL,
        principal   TEXT NOT NULL,
        reason      TEXT,
        recalled_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_recall_log_claim ON recall_log (claim_id)",

    # Sieve rejection log: every push the sieve rejects gets a row
    # for audit. The kb_rejections MCP tool reads from here.
    """
    CREATE TABLE IF NOT EXISTS sieve_rejections (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        principal       TEXT NOT NULL,
        reason_code     TEXT NOT NULL,
        matched_pattern TEXT,
        payload_excerpt TEXT,
        rejected_at     TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_sieve_rejections_principal ON sieve_rejections (principal)",
    "CREATE INDEX IF NOT EXISTS idx_sieve_rejections_reason    ON sieve_rejections (reason_code)",
]


# Mirror sqlite/storage._ENTITY_TABLE so the same enum drives both.
_ENTITY_TABLE: dict[EntityType, str] = {
    EntityType.KNOWLEDGE: "knowledge",
    EntityType.NEGATIVE:  "negative_knowledge",
    EntityType.ERROR:     "errors",
    EntityType.RULE:      "rules",
}

# Tables this adapter owns. Used by truncate_all() for the test fixture.
_OWNED_TABLES: list[str] = [
    "relations",
    "snapshots",
    "sessions",
    "rules",
    "errors",
    "negative_knowledge",
    "knowledge",
    "_mcm_versions",
    # LODESTONE additive tables.
    "sieve_rejections",
    "recall_log",
    "tokens",
]


# ---------------------------------------------------------------------------
# Row hydration helpers — convert dict_row mappings to backend dataclasses.
# ---------------------------------------------------------------------------


def _as_dt(v: Any) -> Optional[datetime]:
    return v if isinstance(v, datetime) else None


def _knowledge_from_row(r: dict[str, Any]) -> KnowledgeRow:
    return KnowledgeRow(
        id=r["id"],
        topic=r["topic"],
        summary=r["summary"],
        kind=r["kind"],
        detail=r["detail"],
        tags=r["tags"],
        project=r["project"],
        rationale=r["rationale"],
        alternatives=r["alternatives"],
        hit_count=r["hit_count"] or 0,
        last_hit_at=_as_dt(r["last_hit_at"]),
        reinforcement_count=r["reinforcement_count"] or 0,
        pinned=bool(r["pinned"]),
        created_at=_as_dt(r["created_at"]),
        updated_at=_as_dt(r["updated_at"]),
    )


def _negative_from_row(r: dict[str, Any]) -> NegativeRow:
    return NegativeRow(
        id=r["id"],
        category=r["category"],
        what_failed=r["what_failed"],
        why_failed=r["why_failed"],
        correct_approach=r["correct_approach"],
        severity=r["severity"],
        project=r["project"],
        pinned=bool(r["pinned"]),
        created_at=_as_dt(r["created_at"]),
    )


def _error_from_row(r: dict[str, Any]) -> ErrorRow:
    return ErrorRow(
        id=r["id"],
        pattern=r["pattern"],
        context=r["context"],
        root_cause=r["root_cause"],
        fix=r["fix"],
        tags=r["tags"],
        project=r["project"],
        pinned=bool(r["pinned"]),
        created_at=_as_dt(r["created_at"]),
    )


def _rule_from_row(r: dict[str, Any]) -> RuleRow:
    return RuleRow(
        id=r["id"],
        title=r["title"],
        keywords=r["keywords"],
        file_path=r["file_path"],
        description=r["description"],
        category=r["category"],
        hit_count=r["hit_count"] or 0,
        last_hit_at=_as_dt(r["last_hit_at"]),
        reinforcement_count=r["reinforcement_count"] or 0,
        pinned=bool(r["pinned"]),
        content_hash=r["content_hash"],
        archived=bool(r["archived"]),
        archived_at=_as_dt(r["archived_at"]),
        created_at=_as_dt(r["created_at"]),
        updated_at=_as_dt(r["updated_at"]),
    )


def _session_from_row(r: dict[str, Any]) -> SessionRow:
    return SessionRow(
        id=r["id"],
        status=r["status"],
        current_task=r["current_task"],
        findings_summary=r["findings_summary"],
        next_steps=r["next_steps"],
        blockers=r["blockers"],
        context_snapshot=r["context_snapshot"],
        created_at=_as_dt(r["created_at"]),
    )


def _snapshot_from_row(r: dict[str, Any]) -> SnapshotRow:
    return SnapshotRow(
        id=r["id"],
        sequence_num=r["sequence_num"],
        session_id=r["session_id"],
        goal=r["goal"],
        progress=r["progress"],
        open_questions=r["open_questions"],
        blockers=r["blockers"],
        next_steps=r["next_steps"],
        active_files=r["active_files"],
        key_decisions=r["key_decisions"],
        created_at=_as_dt(r["created_at"]),
    )


def _relation_from_row(r: dict[str, Any]) -> RelationRow:
    return RelationRow(
        id=r["id"],
        source_type=EntityType(r["source_type"]),
        source_id=r["source_id"],
        target_type=EntityType(r["target_type"]),
        target_id=r["target_id"],
        relation=r["relation"],
        note=r["note"],
        created_at=_as_dt(r["created_at"]),
    )


# ---------------------------------------------------------------------------
# PostgresStorage
# ---------------------------------------------------------------------------


class PostgresStorage:
    """StorageBackend on Postgres 15+ using psycopg3.

    Constructed with a DSN. The adapter manages a single connection in
    autocommit-off mode, committing per write operation to match the
    SqliteStorage reference's semantics (commit-after-write).
    """

    CONTRACT_VERSION: int = CONTRACT_VERSION
    capabilities: set[Capability] = set()

    def __init__(self, dsn: str, *, conn: Optional["psycopg.Connection"] = None):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as e:
            raise MissingDependencyError(
                "PostgresStorage requires psycopg. "
                "Install with: pip install 'mcm-engine[postgres]'"
            ) from e
        self._psycopg = psycopg
        self._dsn = dsn
        if conn is None:
            conn = psycopg.connect(dsn, row_factory=dict_row)
        else:
            conn.row_factory = dict_row
        self._conn = conn

    # ---- Schema management ----

    def ensure_schema(self) -> None:
        with self._conn.cursor() as cur:
            for stmt in _DDL_STATEMENTS:
                cur.execute(stmt)
        self._conn.commit()

    def truncate_all(self) -> None:
        """Test-only convenience: wipe every owned table and reset
        identity sequences. Not part of the StorageBackend Protocol."""
        with self._conn.cursor() as cur:
            cur.execute(
                "TRUNCATE TABLE "
                + ", ".join(_OWNED_TABLES)
                + " RESTART IDENTITY CASCADE"
            )
        self._conn.commit()

    # ---- Knowledge ----

    def find_knowledge_by_topic_kind(
        self, topic: str, kind: str, *, caller: Optional[str] = None,
    ) -> Optional[KnowledgeRow]:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM knowledge WHERE topic = %s AND kind = %s",
                (topic, kind),
            )
            r = cur.fetchone()
        return _knowledge_from_row(r) if r else None

    def find_similar_knowledge(
        self, topic: str, *, caller: Optional[str] = None,
    ) -> Optional[KnowledgeRow]:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM knowledge "
                "WHERE tsv @@ plainto_tsquery('english', %s) "
                "ORDER BY ts_rank_cd(tsv, plainto_tsquery('english', %s)) DESC "
                "LIMIT 1",
                (topic, topic),
            )
            r = cur.fetchone()
        return _knowledge_from_row(r) if r else None

    def insert_knowledge(self, row: KnowledgeRow) -> int:
        with self._conn.cursor() as cur:
            if row.id:
                cur.execute(
                    "INSERT INTO knowledge "
                    "(id, topic, kind, summary, detail, tags, project, rationale, alternatives) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.id, row.topic, row.kind, row.summary, row.detail, row.tags,
                     row.project, row.rationale, row.alternatives),
                )
            else:
                cur.execute(
                    "INSERT INTO knowledge "
                    "(topic, kind, summary, detail, tags, project, rationale, alternatives) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.topic, row.kind, row.summary, row.detail, row.tags,
                     row.project, row.rationale, row.alternatives),
                )
            new_id = cur.fetchone()["id"]
        self._conn.commit()
        return new_id

    def update_knowledge(self, knowledge_id: int, **fields: Any) -> None:
        if not fields:
            return
        allowed = {"topic", "kind", "summary", "detail", "tags", "project",
                   "rationale", "alternatives"}
        bad = set(fields) - allowed
        if bad:
            raise ValueError(f"unknown knowledge fields: {sorted(bad)}")
        cols = ", ".join(f"{k} = %s" for k in fields)
        values = tuple(fields.values()) + (knowledge_id,)
        with self._conn.cursor() as cur:
            cur.execute(
                f"UPDATE knowledge SET {cols}, updated_at = now() WHERE id = %s",
                values,
            )
        self._conn.commit()

    # ---- Negative ----

    def insert_negative(self, row: NegativeRow) -> int:
        with self._conn.cursor() as cur:
            if row.id:
                cur.execute(
                    "INSERT INTO negative_knowledge "
                    "(id, category, what_failed, why_failed, correct_approach, severity, project) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.id, row.category, row.what_failed, row.why_failed,
                     row.correct_approach, row.severity, row.project),
                )
            else:
                cur.execute(
                    "INSERT INTO negative_knowledge "
                    "(category, what_failed, why_failed, correct_approach, severity, project) "
                    "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.category, row.what_failed, row.why_failed,
                     row.correct_approach, row.severity, row.project),
                )
            new_id = cur.fetchone()["id"]
        self._conn.commit()
        return new_id

    # ---- Errors ----

    def insert_error(self, row: ErrorRow) -> int:
        with self._conn.cursor() as cur:
            if row.id:
                cur.execute(
                    "INSERT INTO errors "
                    "(id, pattern, context, root_cause, fix, tags, project) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.id, row.pattern, row.context, row.root_cause, row.fix,
                     row.tags, row.project),
                )
            else:
                cur.execute(
                    "INSERT INTO errors "
                    "(pattern, context, root_cause, fix, tags, project) "
                    "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.pattern, row.context, row.root_cause, row.fix,
                     row.tags, row.project),
                )
            new_id = cur.fetchone()["id"]
        self._conn.commit()
        return new_id

    # ---- Rules ----

    def find_rule_by_title(
        self, title: str, *, caller: Optional[str] = None,
    ) -> Optional[RuleRow]:
        with self._conn.cursor() as cur:
            cur.execute("SELECT * FROM rules WHERE title = %s", (title,))
            r = cur.fetchone()
        return _rule_from_row(r) if r else None

    def find_rule_by_file_path(
        self, file_path: str, *, caller: Optional[str] = None,
    ) -> Optional[RuleRow]:
        with self._conn.cursor() as cur:
            cur.execute("SELECT * FROM rules WHERE file_path = %s", (file_path,))
            r = cur.fetchone()
        return _rule_from_row(r) if r else None

    def insert_rule(self, row: RuleRow) -> int:
        with self._conn.cursor() as cur:
            if row.id:
                cur.execute(
                    "INSERT INTO rules "
                    "(id, title, keywords, file_path, description, category, content_hash) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.id, row.title, row.keywords, row.file_path, row.description,
                     row.category, row.content_hash),
                )
            else:
                cur.execute(
                    "INSERT INTO rules "
                    "(title, keywords, file_path, description, category, content_hash) "
                    "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.title, row.keywords, row.file_path, row.description,
                     row.category, row.content_hash),
                )
            new_id = cur.fetchone()["id"]
        self._conn.commit()
        return new_id

    def update_rule(self, rule_id: int, **fields: Any) -> None:
        if not fields:
            return
        allowed = {"title", "keywords", "file_path", "description", "category",
                   "content_hash"}
        bad = set(fields) - allowed
        if bad:
            raise ValueError(f"unknown rule fields: {sorted(bad)}")
        cols = ", ".join(f"{k} = %s" for k in fields)
        values = tuple(fields.values()) + (rule_id,)
        with self._conn.cursor() as cur:
            cur.execute(
                f"UPDATE rules SET {cols}, updated_at = now() WHERE id = %s",
                values,
            )
        self._conn.commit()

    def list_rules_with_file_paths(
        self, *, caller: Optional[str] = None,
    ) -> list[RuleRow]:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM rules "
                "WHERE file_path IS NOT NULL AND file_path != ''"
            )
            rows = cur.fetchall()
        return [_rule_from_row(r) for r in rows]

    def soft_delete_rule(self, rule_id: int) -> None:
        with self._conn.cursor() as cur:
            cur.execute(
                "UPDATE rules SET archived = TRUE, archived_at = now(), "
                "updated_at = now() WHERE id = %s",
                (rule_id,),
            )
        self._conn.commit()

    def restore_rule(self, rule_id: int) -> None:
        with self._conn.cursor() as cur:
            cur.execute(
                "UPDATE rules SET archived = FALSE, archived_at = NULL, "
                "updated_at = now() WHERE id = %s",
                (rule_id,),
            )
        self._conn.commit()

    # ---- Relations ----

    def insert_relation(self, row: RelationRow) -> Optional[int]:
        try:
            with self._conn.cursor() as cur:
                if row.id:
                    cur.execute(
                        "INSERT INTO relations "
                        "(id, source_type, source_id, target_type, target_id, relation, note) "
                        "VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id",
                        (row.id, row.source_type.value, row.source_id,
                         row.target_type.value, row.target_id,
                         row.relation, row.note),
                    )
                else:
                    cur.execute(
                        "INSERT INTO relations "
                        "(source_type, source_id, target_type, target_id, relation, note) "
                        "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                        (row.source_type.value, row.source_id,
                         row.target_type.value, row.target_id,
                         row.relation, row.note),
                    )
                new_id = cur.fetchone()["id"]
            self._conn.commit()
            return new_id
        except self._psycopg.errors.UniqueViolation:
            self._conn.rollback()
            return None

    def list_outgoing_relations(
        self, source_type: EntityType, source_id: int,
        *, caller: Optional[str] = None,
    ) -> list[RelationRow]:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM relations "
                "WHERE source_type = %s AND source_id = %s",
                (source_type.value, source_id),
            )
            rows = cur.fetchall()
        return [_relation_from_row(r) for r in rows]

    def list_incoming_relations(
        self, target_type: EntityType, target_id: int,
        *, caller: Optional[str] = None,
    ) -> list[RelationRow]:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM relations "
                "WHERE target_type = %s AND target_id = %s",
                (target_type.value, target_id),
            )
            rows = cur.fetchall()
        return [_relation_from_row(r) for r in rows]

    # ---- Sessions + snapshots ----

    def insert_session(self, row: SessionRow) -> int:
        with self._conn.cursor() as cur:
            if row.id:
                cur.execute(
                    "INSERT INTO sessions "
                    "(id, status, current_task, findings_summary, next_steps, blockers, context_snapshot) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.id, row.status, row.current_task, row.findings_summary,
                     row.next_steps, row.blockers, row.context_snapshot),
                )
            else:
                cur.execute(
                    "INSERT INTO sessions "
                    "(status, current_task, findings_summary, next_steps, blockers, context_snapshot) "
                    "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.status, row.current_task, row.findings_summary,
                     row.next_steps, row.blockers, row.context_snapshot),
                )
            new_id = cur.fetchone()["id"]
        self._conn.commit()
        return new_id

    def get_last_session(
        self, *, caller: Optional[str] = None,
    ) -> Optional[SessionRow]:
        with self._conn.cursor() as cur:
            cur.execute("SELECT * FROM sessions ORDER BY id DESC LIMIT 1")
            r = cur.fetchone()
        return _session_from_row(r) if r else None

    def next_snapshot_seq(self, session_id: Optional[int]) -> int:
        with self._conn.cursor() as cur:
            if session_id is None:
                cur.execute(
                    "SELECT COALESCE(MAX(sequence_num), 0) + 1 AS next_seq "
                    "FROM snapshots WHERE session_id IS NULL"
                )
            else:
                cur.execute(
                    "SELECT COALESCE(MAX(sequence_num), 0) + 1 AS next_seq "
                    "FROM snapshots WHERE session_id = %s",
                    (session_id,),
                )
            r = cur.fetchone()
        return r["next_seq"]

    def insert_snapshot(self, row: SnapshotRow) -> int:
        with self._conn.cursor() as cur:
            if row.id:
                cur.execute(
                    "INSERT INTO snapshots "
                    "(id, session_id, sequence_num, goal, progress, open_questions, blockers, "
                    " next_steps, active_files, key_decisions) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.id, row.session_id, row.sequence_num, row.goal, row.progress,
                     row.open_questions, row.blockers, row.next_steps,
                     row.active_files, row.key_decisions),
                )
            else:
                cur.execute(
                    "INSERT INTO snapshots "
                    "(session_id, sequence_num, goal, progress, open_questions, blockers, "
                    " next_steps, active_files, key_decisions) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
                    (row.session_id, row.sequence_num, row.goal, row.progress,
                     row.open_questions, row.blockers, row.next_steps,
                     row.active_files, row.key_decisions),
                )
            new_id = cur.fetchone()["id"]
        self._conn.commit()
        return new_id

    def get_last_snapshot(
        self, *, caller: Optional[str] = None,
    ) -> Optional[SnapshotRow]:
        with self._conn.cursor() as cur:
            cur.execute("SELECT * FROM snapshots ORDER BY id DESC LIMIT 1")
            r = cur.fetchone()
        return _snapshot_from_row(r) if r else None

    # ---- Cross-entity (enum-driven) ----

    def set_pinned(self, entity_type: EntityType, entity_id: int, value: bool) -> None:
        table = _ENTITY_TABLE[entity_type]
        with self._conn.cursor() as cur:
            cur.execute(
                f"UPDATE {table} SET pinned = %s WHERE id = %s",
                (bool(value), entity_id),
            )
        self._conn.commit()

    def count_by_type(
        self,
        entity_type: EntityType,
        *,
        project: Optional[str] = None,
        pinned: Optional[bool] = None,
        caller: Optional[str] = None,
    ) -> int:
        table = _ENTITY_TABLE[entity_type]
        clauses: list[str] = []
        params: list[Any] = []
        if project is not None:
            if table == "rules":
                raise ValueError("rules has no project column; do not pass project=")
            clauses.append("project = %s")
            params.append(project)
        if pinned is not None:
            clauses.append("pinned = %s")
            params.append(bool(pinned))
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        with self._conn.cursor() as cur:
            cur.execute(f"SELECT COUNT(*) AS cnt FROM {table}{where}", tuple(params))
            r = cur.fetchone()
        return r["cnt"]

    def list_pinned(
        self, entity_type: EntityType, *, caller: Optional[str] = None,
    ) -> list[Any]:
        table = _ENTITY_TABLE[entity_type]
        with self._conn.cursor() as cur:
            cur.execute(f"SELECT * FROM {table} WHERE pinned = TRUE ORDER BY id")
            rows = cur.fetchall()
        if entity_type is EntityType.KNOWLEDGE:
            return [_knowledge_from_row(r) for r in rows]
        if entity_type is EntityType.NEGATIVE:
            return [_negative_from_row(r) for r in rows]
        if entity_type is EntityType.ERROR:
            return [_error_from_row(r) for r in rows]
        if entity_type is EntityType.RULE:
            return [_rule_from_row(r) for r in rows]
        raise ValueError(f"unknown EntityType {entity_type}")

    def entry_exists(
        self, entity_type: EntityType, entity_id: int,
        *, caller: Optional[str] = None,
    ) -> bool:
        table = _ENTITY_TABLE[entity_type]
        with self._conn.cursor() as cur:
            cur.execute(
                f"SELECT 1 FROM {table} WHERE id = %s LIMIT 1",
                (entity_id,),
            )
            r = cur.fetchone()
        return r is not None

    def find_by_id(
        self, entity_type: EntityType, entity_id: int,
        *, caller: Optional[str] = None,
    ) -> Optional[Any]:
        table = _ENTITY_TABLE[entity_type]
        with self._conn.cursor() as cur:
            cur.execute(f"SELECT * FROM {table} WHERE id = %s", (entity_id,))
            row = cur.fetchone()
        if row is None:
            return None
        if entity_type is EntityType.KNOWLEDGE:
            return _knowledge_from_row(row)
        if entity_type is EntityType.NEGATIVE:
            return _negative_from_row(row)
        if entity_type is EntityType.ERROR:
            return _error_from_row(row)
        if entity_type is EntityType.RULE:
            return _rule_from_row(row)
        raise ValueError(f"unknown EntityType {entity_type}")

    # ---- Bulk iteration (migrate CLI) ----

    def iter_entries(
        self, entity_type: EntityType, *, caller: Optional[str] = None,
    ) -> Iterator[Any]:
        table = _ENTITY_TABLE[entity_type]
        hydrate = {
            EntityType.KNOWLEDGE: _knowledge_from_row,
            EntityType.NEGATIVE:  _negative_from_row,
            EntityType.ERROR:     _error_from_row,
            EntityType.RULE:      _rule_from_row,
        }[entity_type]
        # Use a server-side cursor so multi-million-row corpora don't
        # materialize entirely in client memory.
        with self._conn.cursor(name="iter_entries") as cur:
            cur.execute(f"SELECT * FROM {table} ORDER BY id")
            for r in cur:
                yield hydrate(r)

    def iter_sessions(
        self, *, caller: Optional[str] = None,
    ) -> Iterator[SessionRow]:
        with self._conn.cursor(name="iter_sessions") as cur:
            cur.execute("SELECT * FROM sessions ORDER BY id")
            for r in cur:
                yield _session_from_row(r)

    def iter_snapshots(
        self, *, caller: Optional[str] = None,
    ) -> Iterator[SnapshotRow]:
        with self._conn.cursor(name="iter_snapshots") as cur:
            cur.execute("SELECT * FROM snapshots ORDER BY id")
            for r in cur:
                yield _snapshot_from_row(r)

    def iter_relations(
        self, *, caller: Optional[str] = None,
    ) -> Iterator[RelationRow]:
        with self._conn.cursor(name="iter_relations") as cur:
            cur.execute("SELECT * FROM relations ORDER BY id")
            for r in cur:
                yield _relation_from_row(r)

    def bump_sequences(self) -> None:
        """Advance every owned table's IDENTITY sequence past its current
        MAX(id). Required after a migration that inserted explicit ids,
        so the next auto-generated id doesn't collide.
        """
        id_tables = [
            "knowledge", "negative_knowledge", "errors", "rules",
            "sessions", "snapshots", "relations",
        ]
        with self._conn.cursor() as cur:
            for table in id_tables:
                cur.execute(
                    f"SELECT setval("
                    f"  pg_get_serial_sequence(%s, 'id'),"
                    f"  COALESCE((SELECT MAX(id) FROM {table}), 1),"
                    f"  (SELECT MAX(id) FROM {table}) IS NOT NULL"
                    f")",
                    (table,),
                )
        self._conn.commit()

    # ---- Engine-wide counters ----

    def count_relations(self, *, caller: Optional[str] = None) -> int:
        with self._conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) AS cnt FROM relations")
            r = cur.fetchone()
        return r["cnt"]

    def count_snapshots(self, *, caller: Optional[str] = None) -> int:
        with self._conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) AS cnt FROM snapshots")
            r = cur.fetchone()
        return r["cnt"]

    def count_recent_knowledge(
        self, since_days: float, *, caller: Optional[str] = None,
    ) -> int:
        # Days-based recency match (sqlite uses julianday; postgres uses
        # interval arithmetic).
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) AS cnt FROM knowledge "
                "WHERE EXTRACT(EPOCH FROM (now() - created_at)) / 86400.0 < %s",
                (float(since_days),),
            )
            r = cur.fetchone()
        return r["cnt"]

    def count_stale_knowledge(
        self,
        threshold_days: float = 90.0,
        *,
        caller: Optional[str] = None,
    ) -> int:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) AS cnt FROM knowledge "
                "WHERE EXTRACT(EPOCH FROM (now() - created_at)) / 86400.0 > %s "
                "AND (last_hit_at IS NULL "
                "     OR EXTRACT(EPOCH FROM (now() - last_hit_at)) / 86400.0 > %s) "
                "AND pinned = FALSE",
                (float(threshold_days), float(threshold_days)),
            )
            r = cur.fetchone()
        return r["cnt"]
