{{- include "mcm-engine.validate" . -}}
{{- $createSecret := or .Values.postgresql.enabled (and (not .Values.postgresql.enabled) .Values.externalDatabase.dsn (not .Values.externalDatabase.existingSecret)) -}}
{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcm-engine.fullname" . }}
  labels:
    {{- include "mcm-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  password: {{ .Values.postgresql.auth.password | quote }}
  dsn: {{ printf "postgresql://%s:%s@%s:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "mcm-engine.postgres.fullname" .) .Values.postgresql.auth.database | quote }}
  {{- else }}
  dsn: {{ .Values.externalDatabase.dsn | quote }}
  {{- end }}
{{- end }}
